(global-set-key (kbd "M-g") 'goto-line)
(global-unset-key (kbd "M-f"))
(global-unset-key (kbd "C-M-f"))
(global-set-key (kbd "M-f M-s") 'save-buffer)
(global-set-key (kbd "M-f s") 'save-buffer)
(global-set-key (kbd "M-f M-o") 'find-file)
(global-set-key (kbd "M-f o") 'find-file)
(global-set-key (kbd "C-M-F o") 'find-file-other-frame)
(global-set-key (kbd "C-<tab>") 'switch-to-buffer)
(global-set-key (kbd "C-<backspace>") 'backward-kill-word)
(global-set-key (kbd "C-z") 'undo)
